# Ejercicios Numpy II

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np

In [4]:
my_array = np.arange(10)
my_array[::-2]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [[8 7]] del array `my_array`

In [14]:
my_array[8:6:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [[2 1 0]] de `my_array`

In [15]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [3]:
matrix = np.arange(1, 21).reshape(4, 5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [26]:
np.transpose(matrix)

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [28]:
matrix[0::2, 0::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [31]:
matrix[:-1, ::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [32]:
# 1)
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

x[x == 'Loro']

array(['Loro', 'Loro'], dtype='<U5')

In [33]:
# 2)
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])


cond = 'Loro'
x[x == cond]

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [42]:
seq = np.arange(20)
a, b = np.split(seq, [10])
a = a.reshape(5, 2)
b = b.reshape(5, 2)
print(a, '\n')
print(b, '\n')

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]] 



## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del **ejercicio 4**
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [5]:
matrix[::-1, ::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [8]:
from sys import getsizeof
zero = np.zeros(10)
print('Memory usage: ', getsizeof(zero))
zero[4] = 1
zero

Memory usage:  184


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [10]:
new_array = np.arange(10, 50)
new_array[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [[1,2,0,0,4,0]]. El output sería [[0, 1, 4]]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [17]:
arr = np.array([1,2,0,0,4,0])
result = np.where(arr != 0)
print('Indexes of values different than 0: ', result[0])

Indexes of values different than 0:  [0 1 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [28]:
new_matrix = np.random.randint(10000, size = (10, 10))
print('Max: ', new_matrix.max())
print('Min: ', new_matrix.min())


Max:  9988
Min:  238


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [33]:
arr2 = np.random.randint(10000, size = (1, 30))
print('Array mean:', arr2.mean())

Array mean: 4471.533333333334


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [43]:
arr3 = np.ones((10, 10))
inner = arr3[1:-1, 1:-1]
inner.fill(0)
arr3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [60]:
iden_2 = np.identity(2)
iden_2_inv = iden_2[::-1]
iden_2_inv = np.concatenate([iden_2_inv, iden_2_inv], axis = 1)
iden_2_inv = np.concatenate([iden_2_inv, iden_2_inv], axis = 1)
iden_2_inv = np.concatenate([iden_2_inv, iden_2_inv])
iden_2_inv = np.concatenate([iden_2_inv, iden_2_inv])
iden_2_inv

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [66]:
np.tile([0, 1], (8, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [69]:
matrix2 = np.random.randint(100000, size = (5, 5))
matrix2_norm = (matrix2 - matrix2.mean())/ matrix2.std()
matrix2_norm

array([[-0.06518453, -0.31597354, -0.617027  ,  1.20621447, -1.30313314],
       [-1.39928967, -0.20776635, -0.212352  ,  1.5858639 , -0.51649811],
       [-1.44951856, -0.07360933,  1.32974273,  1.03938912,  0.79005756],
       [ 0.51964622, -1.61079847,  0.48509385,  1.48647253, -0.02042997],
       [-1.47134485, -1.0504601 , -0.20360727,  0.73460315,  1.33990937]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [75]:
seq2 = np.arange(11)
to_replace = seq2[3:9]
to_replace.fill(-1)
seq2[seq2 > 0]

array([ 1,  2,  9, 10])

## Ejercicio 21 
#### Bonus track. Mini hundir la flota para ir practicando.
##### Te ayudará a entender la lógica de la tarea Hundir la Flota.
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.